services:
  app:
    build: . 
    env_file:
      - .env 
    ports:
      - 8020:8020
    networks:
      - net
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15.7-alpine3.20
    env_file:
      - .env 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql
    networks:
      - net
    restart: always

networks:
  net:
  
volumes:
  db:

